name: ArmorTier
version: '${project.version}'
main: net.daechler.armortier.ArmorTier
api-version: '1.20'
authors: [Daechler]
description: Let only players of the same fighting class fight against each other.
